/**
 * Match Descriptor Contract
 *
 * The sole handoff value between any intent producer (queue, tournament bracket,
 * lobby, direct invite) and the Session that runs a game.
 *
 * OWNERSHIP
 *   This is a value, not a service. The producer emits it and forgets. There is
 *   no callback, no shared state, no ongoing relationship.
 *
 * PRODUCER
 *   Any intent producer: Matchmaking (FCFS Queue), tournament bracket, lobby,
 *   invite, or bot match generator. All producers emit the same shape.
 *
 * CONSUMER
 *   Session — the sole consumer. Receives the Descriptor exactly once, uses it
 *   to initialise the game instance, and never communicates back to the producer.
 *
 * IMMUTABILITY
 *   Once created, no domain may modify a Match Descriptor. If it is invalid,
 *   Session rejects it at initialisation — it does not attempt to repair it.
 *
 * EXCLUDED (intentionally)
 *   Rules / game logic  → belongs to Variant
 *   Session mechanics   → Session's domain
 *   Transport details   → mapped by Transport at connection time
 *   Rating values       → ratings read by Matchmaking for pairing, not carried here
 */

// ─────────────────────────────────────────────────────────────────────────────
// Supporting types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * How many sides and participants per side this game has.
 * Declared by the Variant; carried in the Descriptor for Session and Matchmaking.
 */
export interface ParticipantCardinality {
  /** Number of competing sides — 2 for standard chess, 4 for four-player variants. */
  readonly sides: number;
  /** Number of participants per side — 1 for standard, 2 for team chess. */
  readonly perSide: number;
}

/** Maps one authenticated participant to their side in the game. */
export interface ParticipantAssignment {
  /** Authenticated user ID — sourced from the Auth layer. */
  readonly userId: string;
  /** Zero-indexed side number (0 = first side / White, 1 = second side / Black, …). */
  readonly side: number;
  /** Display name at match time, sourced from the Auth layer. Absent if the user has none set. */
  readonly name?: string;
  /** Avatar URL at match time, sourced from the Auth layer. Absent if the user has none set. */
  readonly image?: string;
}

/**
 * Clock configuration for the game.
 *
 * Opaque to all domains except Session (sole clock authority).
 * Carried in the Descriptor so the intent producer sets the time control.
 */
export interface TimeControl {
  /** Each side's starting clock value, in seconds. */
  readonly initialSeconds: number;
  /**
   * Seconds added to the moving side's clock after each move (Fischer increment).
   * 0 = no increment.
   */
  readonly incrementSeconds: number;
  /** Human-readable label for display purposes, e.g. "5+3 Blitz". */
  readonly label: string;
}

/**
 * How the match was created.
 * Flows through the Descriptor → Session → Result for audit and tournament aggregation.
 */
export type MatchProvenance =
  | "queue"       // Matchmaking queue
  | "tournament"  // Tournament bracket engine
  | "invite"      // Direct / friend invite
  | "bot"         // Bot match
  | "internal";   // System-generated (testing, seeding)

// ─────────────────────────────────────────────────────────────────────────────
// Primary contract
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The immutable Match Descriptor.
 *
 * Required fields must always be present and valid before Session initialisation.
 * Optional fields may be absent; consumers must not error on missing optional fields.
 */
export interface MatchDescriptor {
  // ── Required ───────────────────────────────────────────────────────────────

  /** Unique identifier for this match — generated by the producer. */
  readonly matchId: string;

  /**
   * All participants and their side assignments.
   * Array length must equal cardinality.sides × cardinality.perSide.
   * No duplicate userId values are permitted.
   */
  readonly participants: readonly ParticipantAssignment[];

  /** Participant structure declared by the Variant. */
  readonly cardinality: ParticipantCardinality;

  /**
   * Identifies which Variant implementation to use.
   * Must correspond to a registered Variant.
   * Examples: "chess960", "standard".
   */
  readonly variantId: string;

  /**
   * Parameters passed directly to the Variant's initialState() and getCardinality().
   * Opaque to every domain except the Variant that matches variantId.
   * Session stores and forwards this; it never inspects the contents.
   */
  readonly variantParams: Readonly<Record<string, unknown>>;

  /** Clock configuration for this game. Interpreted and enforced by Session. */
  readonly timeControl: TimeControl;

  /** Whether this game contributes to rated rankings. */
  readonly rated: boolean;

  /** How this match was created. Flows through to Result for audit. */
  readonly provenance: MatchProvenance;

  /** ISO 8601 timestamp of Descriptor creation. Set by the producer at emission time. */
  readonly createdAt: string;

  // ── Optional ───────────────────────────────────────────────────────────────

  /**
   * Rating pool this game belongs to.
   * Present only when rated = true and rating pools are configured.
   */
  readonly ratingPoolId?: string;

  /**
   * Tournament-specific context — present only when provenance = "tournament".
   * Opaque to all domains except the tournament engine that produced it.
   * Flows through to Result.tournamentContext unchanged.
   */
  readonly tournamentContext?: Readonly<Record<string, unknown>>;

  /**
   * Arbitrary producer metadata for audit purposes.
   * Flows through to Result.metadata unchanged.
   * No domain acts on this value.
   */
  readonly metadata?: Readonly<Record<string, unknown>>;
}
